config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "conspiracies#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users

  resources :conspiracies, only: [:index, :new, :create, :show, :update] do
    resources :comments, only: [:new, :create]
  end
  resources :votes, only: [:new, :create, :destroy]
  resources :chats do
    resources :messages, only: [:create]
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :conspiracies
  has_many :comments
  has_many :votes

  validates :user_name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @conspiracies = @user.conspiracies
  end
end

app/views/users/show.html.erb
<div class="row">
  <div class="col-10 row background-color-index justify-content-center g-0 ps-2">
    <% @conspiracies.each do |conspiracy| %>
      <div class="card-product col-11 row mx-3 my-3 px-3 py-3">
        <div class="col-10 justify-content-between d-flex flex-column">
          <h3>
            <%= link_to conspiracy_path(conspiracy) do %>
              <%= conspiracy.title %>
            <%end%>
          </h3>
          <p><%= conspiracy.content%> </p>
        </div>

        <div class="col-2 votes mb-3 d-flex flex-column align-items-center">
          <%= link_to conspiracies_path, class: "btn w-100" do %>
            <%= conspiracy.comments.count %> <i class="fa-solid fa-comments fa-rotate-by fa-lg" style="color: #ff5c42; --fa-rotate-angle: 2259266deg;"></i>
          <% end %>
          <%= render "shared/vote_btn", conspiracy: conspiracy %>
          <%= link_to "", root_path(conspiracy), class: "card-trip-link" %>
        </div>

      </div>
    <% end %>

  </div>

  <div class="col-2 side-bar">
    <%= link_to "Add a New Conspiracy", new_conspiracy_path, class: "btn btn-secondary mx-3 my-3 new-conspiracy-btn add-button" %>
  </div>

</div>
</div>