config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "conspiracies#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users

  resources :conspiracies, only: [:index, :new, :create, :show, :update] do
    resources :comments, only: [:new, :create]
  end
  resources :votes, only: [:new, :create, :destroy]
  resources :chats do
    resources :messages, only: [:create]
  end

end

app/models/conspiracy.rb
class Conspiracy < ApplicationRecord
  belongs_to :user
  has_many :votes
  has_many :comments
end

app/controllers/conspiracies_controller.rb
class ConspiraciesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]


def index
  @conspiracies = Conspiracy.where.not(content: [nil, ""])
  @conspiracies = @conspiracies.where.not(title: [nil, ""])
end

  def show
    @conspiracy = Conspiracy.find(params[:id])
    @comment = Comment.create(conspiracy: @conspiracy)
  end

  def new
    @conspiracy = Conspiracy.new
    @chat = Chat.new
  end

  def create
    chat_id = params[:chat_id] || params.dig(:conspiracy, :chat_id)
    chat = Chat.find(chat_id)
    ai_message = chat.messages.where(role: "assistant").order(created_at: :desc).first

    unless ai_message
      redirect_to chat_path(chat), alert: "There is no AI response to save yet"
      return
    end

    # title, content = extract_title_and_content(ai_message.content)

    @conspiracy = Conspiracy.new(user: current_user, title: title, content: content)
    if @conspiracy.save
      redirect_to conspiracy_path(@conspiracy), notice: "Conspiracy created!"
    else
      redirect_to chat_path(chat), alert: @conspiracy.errors.full_messages.to_sentence
    end
  end

  def update
    @conspiracy = Conspiracy.find(params[:id])
    chat_id = params[:chat_id] || params.dig(:conspiracy, :chat_id)
    chat = Chat.find(chat_id)
    ai_message = chat.messages.where(role: "assistant").order(created_at: :desc).first

    if @conspiracy.content.nil?
      @conspiracy.content = ai_message.content
      @conspiracy.save
      @message = Message.new(content: "Can you generate a title?", role: "user", chat: chat)
      AiMessageService.new(@message).call
      redirect_to chat_path(chat) # turbo
    else
      @conspiracy.title = ai_message.content
      @conspiracy.save
      redirect_to conspiracy_path(@conspiracy)
    end
  end
end

app/views/conspiracies/_save_form.html.erb
<%= simple_form_for chat.conspiracy, html: {
      data: {
        controller: "alert",
        alert_icon_value: "warning",
        alert_title_value: "Are your sure?",
        alert_html_value: "You won't be able to edit it later",
        alert_confirm_button_text_value: "All good!",
        alert_show_cancel_button_value: true,
        alert_cancel_button_text_value: "Cancel",
        action: "submit->alert#initSweetalert",
        turbo: false
      } } do |f| %>
  <%= hidden_field_tag :chat_id, chat.id %>
  <% if chat.conspiracy.content.nil? %>
    <%= f.button :submit, '✅ Confirm content', class: 'btn btn-success w-100', id: 'save' %>
  <% else %>
    <%= f.button :submit, '✅ Confirm title', class: 'btn btn-success w-100', id: 'save' %>
  <% end %>
<% end %>

app/views/conspiracies/_vote_btn.html.erb
<%# <div id="conspiracy-vote-<%= conspiracy.id %>">
<%= conspiracy.votes.count %> votes<%= button_to votes_path(conspiracy_id: conspiracy.id), method: :post, class: "btn btn-secondary " do%>
  <i class="fa-solid fa-eye"></i>
<% end %>
</div>
%>

app/views/conspiracies/index.html.erb
<div class="row">
  <div class="col-10 row background-color-index justify-content-center g-0 ps-2">
    <% @conspiracies.each do |conspiracy| %>
      <div class="card-product col-11 mx-3 my-3 p-3"> <!-- removed `row` -->
        <a href="<%= conspiracy_path(conspiracy) %>" class="card-trip-link" aria-label="Open"></a>

        <div class="card-content">
          <h3><%= link_to conspiracy.title, conspiracy_path(conspiracy) %></h3>
          <p><%= conspiracy.content %></p>
        </div>

        <div class="votes">
          <%= link_to conspiracies_path, class: "btn btn-secondary vote-btn w-100" do %>
            <%= conspiracy.comments.count %>
            <i class="fa-solid fa-comments fa-lg"></i>
          <% end %>
          <%= render "shared/vote_btn", conspiracy: conspiracy %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-2 side-bar">
    <%= link_to "Add a New Conspiracy", new_conspiracy_path, class: "btn btn-secondary mx-3 my-3 new-conspiracy-btn add-button" %>
  </div>
</div>
<%# <%= link_to "Create a New Conspiracy", new_conspiracy_path, class: "btn btn-primary mx-3 mt-3" %>
<%# <%= link_to "Create a New Conspiracy", new_conspiracy_path, class: "btn btn-primary mx-3 mt-3" %>

app/views/conspiracies/new.html.erb
<div class="container d-flex">
  <div class="form w-100">
    <h1 class="text-center p-4 bordersm">🔮 Connect the dots 🔮</h1>
    <h5 class="text-gray-600 my-3 text-center">"Fuse two ideas to reveal what they don’t want you to know. 🔵💊🔴"</h5>
    <div class="text-center my-3">
      <%= simple_form_for @chat do |f|%>
        <%= text_field_tag :varone, "", placeholder: "Piece the puzzle 🧩", required: true, class: "bordersm text-center w-full p-5 text-lg mb-6 "%>
        <%= text_field_tag :vartwo, "", placeholder: "🕵🏻‍♂️The secret connection", required: true, class: "bordersm text-center w-full p-5 text-lg mb-6 "%>
      <div class="text-center mt-2">
        <%= f.submit "Reveal the Conspiracy", class: "w-full text-center py-3 bg-gradient-to-r from-purple-600 to-blue-500 text-black font-bold rounded-xl shadow-lg hover:scale-105 transform transition" %>
          </div>
      <% end %>
  </div>
</div>

app/views/conspiracies/show.html.erb
<div class="container d-flex justify-content-center">
  <div class="card-product mx-3 my-3 px-3 py-3 h-100 w-100 flex-column">
    <h1><%= @conspiracy.title %></h1>
    <div class="conspiracy_author text-end">
      <h3> Created by - <%= (@conspiracy.user.user_name).capitalize %></h3>
    </div>
    <div class="conspiracy content">
      <%= @conspiracy.content %>
      <div class= "vote d-flex">
        <%= render "shared/vote_btn", conspiracy: @conspiracy %>
      </div>
      <%# render comment form here %>
      <div class= "comment d-flex">
        <%= render "shared/comment_form", conspiracy: @conspiracy, comment:Comment.new %>
      </div>
      <div id="comments">
        <%= render "shared/comments_section", conspiracy: @conspiracy %>
      </div>
    </div>
  </div>
</div>